# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('napster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('filename', models.CharField(max_length=65535, primary_key=True, serialize=False)),
                ('filehash', models.CharField(max_length=65535)),
            ],
        ),
        migrations.CreateModel(
            name='UserFileMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napster.File')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='napster.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userfilemap',
            unique_together=set([('user_id', 'filename')]),
        ),
    ]
