# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napster', '0002_auto_20160312_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilemap',
            old_name='filename',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='userfilemap',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfilemap',
            unique_together=set([('user', 'file')]),
        ),
    ]
